/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { MatchResults, RouterHistory } from "@stencil-community/router";
import { IconDefinition } from "@fortawesome/fontawesome-svg-core";
export namespace Components {
    interface AppHome {
        "history": RouterHistory;
    }
    interface AppProfile {
        "match": MatchResults;
    }
    interface AppRoot {
    }
    interface TrendingPage {
        "history": RouterHistory;
    }
    interface VideoPage {
        "match": MatchResults;
    }
    interface VideoPlayer {
        "src": string;
    }
    interface XIcon {
        "icon": IconDefinition;
        "mask"?: IconDefinition;
        "size"?: string;
        "spin": boolean;
    }
}
declare global {
    interface HTMLAppHomeElement extends Components.AppHome, HTMLStencilElement {
    }
    var HTMLAppHomeElement: {
        prototype: HTMLAppHomeElement;
        new (): HTMLAppHomeElement;
    };
    interface HTMLAppProfileElement extends Components.AppProfile, HTMLStencilElement {
    }
    var HTMLAppProfileElement: {
        prototype: HTMLAppProfileElement;
        new (): HTMLAppProfileElement;
    };
    interface HTMLAppRootElement extends Components.AppRoot, HTMLStencilElement {
    }
    var HTMLAppRootElement: {
        prototype: HTMLAppRootElement;
        new (): HTMLAppRootElement;
    };
    interface HTMLTrendingPageElement extends Components.TrendingPage, HTMLStencilElement {
    }
    var HTMLTrendingPageElement: {
        prototype: HTMLTrendingPageElement;
        new (): HTMLTrendingPageElement;
    };
    interface HTMLVideoPageElement extends Components.VideoPage, HTMLStencilElement {
    }
    var HTMLVideoPageElement: {
        prototype: HTMLVideoPageElement;
        new (): HTMLVideoPageElement;
    };
    interface HTMLVideoPlayerElement extends Components.VideoPlayer, HTMLStencilElement {
    }
    var HTMLVideoPlayerElement: {
        prototype: HTMLVideoPlayerElement;
        new (): HTMLVideoPlayerElement;
    };
    interface HTMLXIconElement extends Components.XIcon, HTMLStencilElement {
    }
    var HTMLXIconElement: {
        prototype: HTMLXIconElement;
        new (): HTMLXIconElement;
    };
    interface HTMLElementTagNameMap {
        "app-home": HTMLAppHomeElement;
        "app-profile": HTMLAppProfileElement;
        "app-root": HTMLAppRootElement;
        "trending-page": HTMLTrendingPageElement;
        "video-page": HTMLVideoPageElement;
        "video-player": HTMLVideoPlayerElement;
        "x-icon": HTMLXIconElement;
    }
}
declare namespace LocalJSX {
    interface AppHome {
        "history"?: RouterHistory;
    }
    interface AppProfile {
        "match"?: MatchResults;
    }
    interface AppRoot {
    }
    interface TrendingPage {
        "history"?: RouterHistory;
    }
    interface VideoPage {
        "match"?: MatchResults;
    }
    interface VideoPlayer {
        "src"?: string;
    }
    interface XIcon {
        "icon"?: IconDefinition;
        "mask"?: IconDefinition;
        "size"?: string;
        "spin"?: boolean;
    }
    interface IntrinsicElements {
        "app-home": AppHome;
        "app-profile": AppProfile;
        "app-root": AppRoot;
        "trending-page": TrendingPage;
        "video-page": VideoPage;
        "video-player": VideoPlayer;
        "x-icon": XIcon;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "app-home": LocalJSX.AppHome & JSXBase.HTMLAttributes<HTMLAppHomeElement>;
            "app-profile": LocalJSX.AppProfile & JSXBase.HTMLAttributes<HTMLAppProfileElement>;
            "app-root": LocalJSX.AppRoot & JSXBase.HTMLAttributes<HTMLAppRootElement>;
            "trending-page": LocalJSX.TrendingPage & JSXBase.HTMLAttributes<HTMLTrendingPageElement>;
            "video-page": LocalJSX.VideoPage & JSXBase.HTMLAttributes<HTMLVideoPageElement>;
            "video-player": LocalJSX.VideoPlayer & JSXBase.HTMLAttributes<HTMLVideoPlayerElement>;
            "x-icon": LocalJSX.XIcon & JSXBase.HTMLAttributes<HTMLXIconElement>;
        }
    }
}
